# Análise de Dados e Boas Práticas
## Análise do cenário competitivo de League of Legends
Hugo Leandro Antunes

## 1. Definição do Problema
O dataset utilizado contém informações de partidas profissionas do jogo eletrônico League of Legends, além de ser de domínio público, e pode ser encontrado em https://oracleselixir.com/, onde é disponibilizado em um Google Drive (https://drive.google.com/drive/u/1/folders/1gLSw0RLjBbtaNy0dgnGQDAZOHIgCe-HH).

O dataset contém informações muito valiosas para análise de jogadores, escolha de campeões, de objetivos, escolha de lado e análises pós partidas. Essas informações são pouquíssimas exploradas pela comunidade de League of Legends brasileira, sendo uma área muito explorável para disseminação de informações e maior compreendimento do cenário competitivo. Para detalhes mais aprofundados sobre o que cada dado significa, explicações gerais do jogo, rotas, campeões, funções e regiões; poderá ser encontrado na documentação ./docs/.

A análise que será explorada aqui tem como objetivo explorar as seguintes questões do cenário competitivo de League of Legends:
- Como as 5 principais ligas se diferenciam entre si em relação a estilo de jogo e prioridade no jogo;
- Quais foram as principais mudanças competitivas no jogo ao decorrer de 10 anos. Temos dados desde 2015, sendo possível fazer uma análise histórica robusta;
- Análise de campeões: como os campeões tem prioridade e como desempenham durante as partidas em determinado ano
Entendo que há uma carência muito grande sobre análises robustas desses dados, diferente do que acontece nos outros esportes, onde há muita falta de dados, jogos eletrônicos tem uma abundância dessas informações, o que é geralmente muito pouco explorada.

In [45]:
# Importing Libraries

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [46]:
url = 'https://raw.githubusercontent.com/hugo-antunes19/analise-dados-puc-hugo-antunes/refs/heads/main/data/2025_LoL_esports_match_data_from_OraclesElixir.csv'
df = pd.read_csv(url, delimiter=',', dtype={2: str})

In [47]:
pd.set_option('display.max_columns', None)
df.head(10)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,1,Blue,top,PatkicaA,oe:player:c659697694306de62d978569b84c344,IziDream,oe:team:84bc703e28859788770611d94cf02ac,1.0,Gnar,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,1592,0,1,2,1,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.1131,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,20156,759.6482,0.401970,681.2186,629.7362,7451.0,9,0.3392,2,0.0754,3,17,0.6407,10668,7145,269.2839,0.289981,9793,NaN,NaN,234.0,234.0,0,NaN,NaN,8.8191,3058.0,4466.0,75.0,3394.0,4603.0,79.0,-336.0,-137.0,-4.0,0.0,0.0,1.0,1.0,0.0,0.0,4531.0,6777.0,119.0,5372.0,6968.0,125.0,-841.0,-191.0,-6.0,0.0,0.0,1.0,1.0,2.0,0.0,6473.0,9072.0,154.0,7012.0,9562.0,154.0,-539.0,-490.0,0.0,1.0,1.0,2.0,2.0,2.0,2.0,9244.0,12552.0,217.0,9020.0,12553.0,200.0,224.0,-1.0,17.0,1.0,1.0,2.0,2.0,4.0,2.0
1,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,2,Blue,jng,Joinze,oe:player:dbdc61a1c41acedcbc7d399727155ac,IziDream,oe:team:84bc703e28859788770611d94cf02ac,1.0,Maokai,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,1592,0,0,3,1,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1131,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4963,187.0477,0.098977,906.9724,954.6106,0.0,7,0.2638,7,0.2638,6,29,1.0930,7429,3906,147.2111,0.158520,7200,NaN,NaN,143.0,11.0,132,NaN,NaN,5.3894,2977.0,3153.0,62.0,3451.0,3687.0,71.0,-474.0,-534.0,-9.0,0.0,0.0,0.0,0.0,1.0,0.0,4461.0,5316.0,97.0,5289.0,5332.0,91.0,-828.0,-16.0,6.0,0.0,0.0,0.0,0.0,3.0,0.0,5668.0,6978.0,118.0,7357.0,8317.0,133.0,-1689.0,-1339.0,-15.0,0.0,1.0,1.0,0.0,5.0,0.0,7040.0,8877.0,139.0,9403.0,10321.0,157.0,-2363.0,-1444.0,-18.0,0.0,1.0,2.0,1.0,7.0,0.0
2,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,3,Blue,mid,Sayn,oe:player:694d028e62f4ea668b206ab752b6f94,IziDream,oe:team:84bc703e28859788770611d94cf02ac,1.0,Hwei,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,1592,0,1,2,0,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1131,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,13952,525.8291,0.278244,366.8593,241.0553,0.0,12,0.4523,3,0.1131,4,20,0.7538,9032,5509,207.6256,0.223581,8050,NaN,NaN,209.0,209.0,0,NaN,NaN,7.8769,3020.0,4584.0,75.0,3425.0,4789.0,91.0,-405.0,-205.0,-16.0,0.0,0.0,0.0,0.0,0.0,0.0,4581.0,6530.0,116.0,5666.0,7031.0,141.0,-1085.0,-501.0,-25.0,0.0,0.0,1.0,1.0,1.0,0.0,6332.0,9111.0,166.0,7990.0,10550.0,195.0,-1658.0,-1439.0,-29.0,0.0,0.0,1.0,1.0,2.0,0.0,8488.0,10669.0,200.0,10040.0,13134.0,241.0,-1552.0,-2465.0,-41.0,1.0,0.0,2.0,1.0,5.0,1.0
3,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,4,Blue,bot,Shiganari,oe:player:90704735ca9fc01f2244f23f6e5d635,IziDream,oe:team:84bc703e28859788770611d94cf02ac,1.0,Jinx,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,1592,0,1,3,1,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1131,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,6898,259.9749,0.137567,479.2085,282.9271,333.0,6,0.2261,2,0.0754,1,10,0.3769,9407,5884,221.7588,0.238801,8925,NaN,NaN,251.0,239.0,12,NaN,NaN,9.4598,3097.0,3403.0,81.0,3519.0,3682.0,92.0,-422.0,-279.0,-11.0,0.0,0.0,0.0,0.0,0.0,0.0,4687.0,5589.0,133.0,5598.0,5789.0,138.0,-911.0,-200.0,-5.0,0.0,0.0,0.0,1.0,1.0,0.0,6782.0,8435.0,183.0,8489.0,9683.0,202.0,-1707.0,-1248.0,-19.0,1.0,0.0,1.0,3.0,1.0,0.0,9097.0,11763.0,251.0,11710.0,12919.0,257.0,-2613.0,-1156.0,-6.0,1.0,1.0,2.0,6.0,2.0,0.0
4,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,5,Blue,sup,Lekcyc,oe:player:74f3f60a44ee916ecc257a5381be756,IziDream,oe:team:84bc703e28859788770611d94cf02ac,1.0,Leona,Vi,Skarner,Corki,K'Sante,Sylas,NaN,NaN,NaN,NaN,NaN,1592,0,0,3,2,3,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1131,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4174,157.3116,0.083242,474.5352,534.1583,0.0,40,1.5075,10,0.3769,9,82,3.0905,5719,2196,82.7638,0.089117,4825,NaN,NaN,38.0,38.0,0,NaN,NaN,1.4322,2114.0,2913.0,20.0,2199.0,2420.0,12.0,-85.0,493.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,3238.0,4058.0,31.0,3410.0,3619.0,17.0,-172.0,439.0,14.0,0.0,0.0,1.0,0.0,2.0,0.0,4220.0,5063.0,35.0,4530.0,4749.0,18.0,-310.0,314.0,17.0,0.0,1.0,1.0,0.0,4.0,0.0,5357.0,6259.0,38.0,6019.0,6993.0,20.0,-662.0,-734.0,18.0,0.0,2.0,2.0,0.0,8.0,0.0
5,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,6,Red,top,Nille,oe:player:2df5432fbfcc85dc85c33e269ebd063,Team Valiant,oe:team:71bd93fd1eab2c2f4ba60305ecabce2,0.0,Renekton,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1592,1,3,2,4,13,3,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.4899,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,14166,533.8945,0.263892,1113.5050,986.0804,4339.0,11,0.4146,4,0.1508,4,26,0.9799,10814,7291,274.7864,0.200738,8650,NaN,NaN,214.0,212.0,2,NaN,NaN,8.0653,3394.0,4603.0,79.0,3058.0,4466.0,75.0,336.0,137.0,4.0,1.0,0.0,0.0,0.0,0.0,1.0,5372.0,6968.0,125.0,4531.0,6777.0,119.0,841.0,191.0,6.0,1.0,2.0,0.0,0.0,0.0,1.0,7012.0,9562.0,154.0,6473.0,9072.0,154.0,539.0,490.0,0.0,2.0,2.0,2.0,1.0,1.0,2.0,9020.0,12553.0,200.0,9244.0,12552.0,217.0,-224.0,1.0,-17.0,2.0,4.0,2.0,1.0,1.0,2.0
6,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,7,Red,jng,SPOOKY,oe:player:11389d6d8a29729807c3cf528a98050,Team Valiant,oe:team:71bd93fd1eab2c2f4ba60305ecabce2,0.0,Ivern,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1592,1,1,0,10,13,3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4899,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4924,185.5779,0.091727,280.4774,234.7236,4231.0,6,0.2261,9,0.3392,4,34,1.2814,10740,7217,271.9975,0.198700,9250,NaN,NaN,166.0,11.0,155,NaN,NaN,6.2563,3451.0,3687.0,71.0,2977.0,3153.0,62.0,474.0,534.0,9.0,0.0,1.0,0.0,0.0,0.0,0.0,5289.0,5332.0,91.0,4461.0,5316.0,97.0,828.0,16.0,-6.0,0.0,3.0,0.0,0.0,0.0,0.0,7357.0,8317.0,133.0,5668.0,6978.0,118.0,1689.0,1339.0,15.0,0.0,5.0,0.0,0.0,1.0,1.0,9403.0,10321.0,157.0,7040.0,8877.0,139.0,2363.0,1444.0,18.0,1.0,7.0,0.0,0.0,1.0,2.0
7,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,8,Red,mid,Nafkelah,oe:player:7b0aeb1bb297b0d44629e94186bcb6a,Team Valiant,oe:team:71bd93fd1eab2c2f4ba60305ecabce2,0.0,Orianna,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1592,1,1,1,8,13,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4899,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,15467,582.9271,0.288128,407.6759,404.7739,3495.0,11,0.4146,11,0.4146,5,35,1.3191,11477,7954,299.7739,0.218993,9375,NaN,NaN,254.0,254.0,0,NaN,NaN,9.5729,3425.0,4789.0,91.0,3020.0,4584.0,75.0,405.0,205.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,5666.0,7031.0,141.0,4581.0,6530.0,116.0,1085.0,501.0,25.0,1.0,1.0,0.0,0.0,0.0,1.0,7990.0,10550.0,195.0,6332.0,9111.0,166.0,1658.0,1439.0,29.0,1.0,2.0,0.0,0.0,0.0,1.0,10040.0,13134.0,241.0,8488.0,10669.0,200.0,1552.0,2465.0,41.0,1.0,5.0,1.0,1.0,0.0,2.0
8,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,9,Red,bot,Soldier,oe:player:de75f2eb439368d9b39281bd0c4bdab,Team Valiant,oe:team:71bd93fd1eab2c2f4ba60305ecabce2,0.0,Varus,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1592,1,8,0,3,13,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4899,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,14474,545.5025,0.269630,323.1784,207.3241,8851.0,8,0.3015,6,0.2261,5,21,0.7915,13632,10109,380.9925,0.278327,10875,NaN,NaN,265.0,253.0,12,NaN,NaN,9.9874,3519.0,3682.0,92.0,3097.0,3403.0,81.0,422.0,279.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,5598.0,5789.0,138.0,4687.0,5589.0,133.0,911.0,200.0,5.0,1.0,1.0,0.0,0.0,0.0,0.0,8489.0,9683.0,202.0,6782.0,8435.0,183.0,1707.0,1248.0,19.0,3.0,1.0,0.0,1.0,0.0,1.0,11710.0,12919.0,257.0,9097.0,11763.0,251.0,2613.0,1156.0,6.0,6.0,2.0,0.0,1.0,1.0,2.0
9,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,10,Red,sup,Steeelback,oe:player:bea6c089fd517fff3bc020290ae48f7,Team Valiant,oe:team:71bd93fd1eab2c2f4ba60305ecabce2,0.0,Braum,Yone,Viktor,Aurora,Nocturne,Jarvan IV,NaN,NaN,NaN,NaN,NaN,1592,1,0,0,11,13,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4899,0.603,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4650,175.2513,0.086623,402.8141,439.3342,1406.0,42,1.5829,5,0.1884,15,80,3.0151,7273,3750,141.3317,0.103242,5275,NaN,NaN,23.0,23.0,0,NaN,NaN,0.8668,2199.0,2420.0,12.0,2114.0,2913.0,20.0,85.0,-493.0,-8.0,0.0,0.0,0.0,0.0,0.0,0.0,3410.0,3619.0,17.0,3238.0,4058.0,31.0,172.0,-439.0,-14.0,0.0,2.0,0.0,0.0,0.0,1.0,4530.0,4749.0,18.0,4220.0,5063.0,35.0,310.0,-314.0,-17.0,0.0,4.0,0.0,0.0,1.0,1.0,6019.0,6993.0,20.0,5357.0,6259.0,38.0,662.0,734.0,-18.0,0.0,8.0,0.0,0.0,2.0,2.0

In [48]:
df.tail(10)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
120626,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,3,Blue,mid,Sinian,oe:player:97e179ee675d0c4345bcd64089d2218,Anyone's Legend,oe:team:ed28f87f0cfdba0a2a8f183cebae73a,1.0,Ahri,Zyra,Udyr,Draven,Ezreal,Varus,NaN,NaN,NaN,NaN,NaN,1805,0,4,2,5,9,22,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.2992,1.0305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,23620,785.1524,0.316325,498.7147,237.2410,3272.0,5,0.1662,2,0.0665,2,11,0.3657,13206,9248,307.4127,0.292304,13200,NaN,NaN,260.0,260.0,0,NaN,NaN,8.6427,3774.0,5093.0,87.0,2968.0,4552.0,68.0,806.0,541.0,19.0,1.0,0.0,0.0,0.0,0.0,1.0,5490.0,7857.0,141.0,4736.0,7358.0,119.0,754.0,499.0,22.0,1.0,0.0,0.0,0.0,1.0,1.0,7901.0,10678.0,183.0,7873.0,10227.0,160.0,28.0,451.0,23.0,2.0,2.0,0.0,2.0,3.0,1.0,11534.0,14132.0,224.0,11409.0,13632.0,192.0,125.0,500.0,32.0,4.0,4.0,1.0,8.0,5.0,2.0
120627,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,4,Blue,bot,TheHang,oe:player:1b9b0d1e4f341b3f5837485f68029e7,Anyone's Legend,oe:team:ed28f87f0cfdba0a2a8f183cebae73a,1.0,Yunara,Zyra,Udyr,Draven,Ezreal,Varus,NaN,NaN,NaN,NaN,NaN,1805,0,3,4,4,9,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2992,1.0305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16561,550.5042,0.221789,679.0803,448.1884,1304.0,7,0.2327,5,0.1662,1,17,0.5651,13305,9347,310.7036,0.295433,13675,NaN,NaN,271.0,261.0,10,NaN,NaN,9.0083,3215.0,3634.0,84.0,3469.0,3188.0,90.0,-254.0,446.0,-6.0,0.0,0.0,0.0,0.0,0.0,0.0,5585.0,5978.0,136.0,5921.0,5521.0,145.0,-336.0,457.0,-9.0,0.0,0.0,0.0,0.0,0.0,0.0,8592.0,8029.0,175.0,8020.0,8146.0,181.0,572.0,-117.0,-6.0,2.0,1.0,1.0,0.0,4.0,1.0,10512.0,10843.0,221.0,9971.0,11356.0,226.0,541.0,-513.0,-5.0,2.0,4.0,2.0,0.0,7.0,2.0
120628,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,5,Blue,sup,Wunai3,oe:player:40049df6e0e1ee46b338c602dd9e1a7,Anyone's Legend,oe:team:ed28f87f0cfdba0a2a8f183cebae73a,1.0,Neeko,Zyra,Udyr,Draven,Ezreal,Varus,NaN,NaN,NaN,NaN,NaN,1805,0,1,5,2,9,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2992,1.0305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4568,151.8449,0.061176,551.1357,229.6953,308.0,56,1.8615,5,0.1662,14,88,2.9252,6533,2575,85.5956,0.081393,5500,NaN,NaN,34.0,34.0,0,NaN,NaN,1.1302,2183.0,2645.0,16.0,2309.0,2931.0,12.0,-126.0,-286.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,3115.0,3316.0,21.0,3620.0,4191.0,31.0,-505.0,-875.0,-10.0,0.0,0.0,1.0,0.0,1.0,0.0,4177.0,4591.0,31.0,4810.0,5576.0,41.0,-633.0,-985.0,-10.0,0.0,0.0,2.0,0.0,2.0,1.0,5518.0,5924.0,31.0,6773.0,8323.0,48.0,-1255.0,-2399.0,-17.0,1.0,1.0,4.0,1.0,9.0,1.0
120629,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,6,Red,top,sasi,oe:player:e85e46c5f3d3fcce55af9ca6a4cb45c,LGD Gaming,oe:team:5f401785b6b78326f9a46b3c6b206ed,0.0,Jax,Jayce,Rumble,Orianna,Nocturne,Aurora,NaN,NaN,NaN,NaN,NaN,1805,1,3,2,6,22,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7313,1.0305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,17377,577.6288,0.178326,891.2244,1024.8532,11667.0,12,0.3989,2,0.0665,2,21,0.6981,14244,10286,341.9169,0.228217,12233,NaN,NaN,270.0,270.0,0,NaN,NaN,8.9751,3476.0,4991.0,79.0,2858.0,4220.0,64.0,618.0,771.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,5141.0,7688.0,128.0,4637.0,7084.0,121.0,504.0,604.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,7290.0,10413.0,160.0,6483.0,9032.0,156.0,807.0,1381.0,4.0,1.0,2.0,1.0,0.0,2.0,1.0,9935.0,14490.0,219.0,8172.0,10972.0,188.0,1763.0,3518.0,31.0,2.0,5.0,2.0,0.0,5.0,3.0
120630,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,7,Red,jng,Heng,oe:player:92f0831b560a15d8be3be25275adb08,LGD Gaming,oe:team:5f401785b6b78326f9a46b3c6b206ed,0.0,Xin Zhao,Jayce,Rumble,Orianna,Nocturne,Aurora,NaN,NaN,NaN,NaN,NaN,1805,1,4,2,12,22,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7313,1.0305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16855,560.2770,0.172969,1467.1579,981.6399,215.0,9,0.2992,8,0.2659,8,42,1.3961,12491,8533,283.6454,0.189324,10600,NaN,NaN,227.0,29.0,198,NaN,NaN,7.5457,3170.0,3503.0,69.0,2921.0,3319.0,61.0,249.0,184.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,5404.0,6230.0,118.0,4435.0,5674.0,97.0,969.0,556.0,21.0,1.0,0.0,0.0,0.0,0.0,0.0,7503.0,8969.0,154.0,6207.0,8069.0,124.0,1296.0,900.0,30.0,2.0,3.0,0.0,0.0,2.0,1.0,9650.0,12425.0,189.0,7900.0,10061.0,144.0,1750.0,2364.0,45.0,2.0,8.0,1.0,1.0,4.0,3.0
120631,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,8,Red,mid,Tangyuan,oe:player:3c93fcbfb525315f6412904e5b9abbd,LGD Gaming,oe:team:5f401785b6b78326f9a46b3c6b206ed,0.0,Sylas,Jayce,Rumble,Orianna,Nocturne,Aurora,NaN,NaN,NaN,NaN,NaN,1805,1,14,2,7,22,10,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.7313,1.0305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,34479,1146.1163,0.353830,947.2687,874.2382,8267.0,7,0.2327,7,0.2327,2,29,0.9640,15880,11922,396.2992,0.264515,15050,NaN,NaN,222.0,217.0,5,NaN,NaN,7.3795,2968.0,4552.0,68.0,3774.0,5093.0,87.0,-806.0,-541.0,-19.0,0.0,0.0,1.0,1.0,0.0,0.0,4736.0,7358.0,119.0,5490.0,7857.0,141.0,-754.0,-499.0,-22.0,0.0,1.0,1.0,1.0,0.0,0.0,7873.0,10227.0,160.0,7901.0,10678.0,183.0,-28.0,-451.0,-23.0,2.0,3.0,1.0,2.0,2.0,0.0,11409.0,13632.0,192.0,11534.0,14132.0,224.0,-125.0,-500.0,-32.0,8.0,5.0,2.0,4.0,4.0,1.0
120632,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,9,Red,bot,Shaoye,oe:player:6d734e1e86b978852d95cfd63d6a643,LGD Gaming,oe:team:5f401785b6b78326f9a46b3c6b206ed,0.0,Caitlyn,Jayce,Rumble,Orianna,Nocturne,Aurora,NaN,NaN,NaN,NaN,NaN,1805,1,0,3,12,22,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7313,1.0305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16264,540.6316,0.166904,404.7756,210.4820,5497.0,14,0.4654,6,0.1994,2,27,0.8975,12977,9019,299.8006,0.200107,11550,NaN,NaN,264.0,252.0,12,NaN,NaN,8.7756,3469.0,3188.0,90.0,3215.0,3634.0,84.0,254.0,-446.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,5921.0,5521.0,145.0,5585.0,5978.0,136.0,336.0,-457.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,8020.0,8146.0,181.0,8592.0,8029.0,175.0,-572.0,117.0,6.0,0.0,4.0,1.0,2.0,1.0,1.0,9971.0,11356.0,226.0,10512.0,10843.0,221.0,-541.0,513.0,5.0,0.0,7.0,2.0,2.0,4.0,2.0
120633,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,10,Red,sup,Ycx,oe:player:397bcf46311de3cf780469b2a842b67,LGD Gaming,oe:team:5f401785b6b78326f9a46b3c6b206ed,0.0,Karma,Jayce,Rumble,Orianna,Nocturne,Aurora,NaN,NaN,NaN,NaN,NaN,1805,1,1,1,18,22,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7313,1.0305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12470,414.5152,0.127970,256.5540,170.9252,797.0,56,1.8615,20,0.6648,17,124,4.1219,9269,5311,176.5429,0.117838,8325,NaN,NaN,57.0,57.0,0,NaN,NaN,1.8947,2309.0,2931.0,12.0,2183.0,2645.0,16.0,126.0,286.0,-4.0,0.0,0.0,0.0,0.0,0.0,0.0,3620.0,4191.0,31.0,3115.0,3316.0,21.0,505.0,875.0,10.0,0.0,1.0,0.0,0.0,0.0,1.0,4810.0,5576.0,41.0,4177.0,4591.0,31.0,633.0,985.0,10.0,0.0,2.0,1.0,0.0,0.0,2.0,6773.0,8323.0,48.0,5518.0,5924.0,31.0,1255.0,2399.0,17.0,1.0,9.0,1.0,1.0,1.0,4.0
120634,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,100,Blue,team,NaN,NaN,Anyone's Legend,oe:team:ed28f87f0cfdba0a2a8f183cebae73a,1.0,NaN,Zyra,Udyr,Draven,Ezreal,Varus,Neeko,Aatrox,Yunara,Renekton,Ahri,1805,0,9,22,20,9,22,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.2992,1.0305,0.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0,11.0,1.0,0.0,2.0,4.0,0.0,3.0,74670,2482.1053,NaN,4104.7978,2906.0609,8201.0,87,2.8920,24,0.7978,30,181,6.0166,51428,31639,1051.7119,NaN,50625,-0.131626,-1.85,NaN,762.0,177,NaN,NaN,31.2133,14951.0,18911.0,312.0,15392.0,19165.0,318.0,-441.0,-254.0,-6.0,1.0,0.0,0.0,0.0,0.0,1.0,23262.0,29909.0,516.0,24822.0,30988.0,541.0,-1560.0,-1079.0,-25.0,1.0,0.0,1.0,1.0,2.0,1.0,33360.0,40399.0,669.0,35496.0,43331.0,696.0,-2136.0,-2932.0,-27.0,4.0,7.0,5.0,5.0,14.0,4.0,43636.0,51932.0,808.0,47738.0,60226.0,874.0,-4102.0,-8294.0,-66.0,8.0,18.0,13.0,13.0,34.0,8.0
120635,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,200,Red,team,NaN,NaN,LGD Gaming,oe:team:5f401785b6b78326f9a46b3c6b206ed,0.0,NaN,Jayce,Rumble,Orianna,Nocturne,Aurora,Jax,Xin Zhao,Karma,Caitlyn,Sylas,1805,1,22,10,55,22,10,4.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,0.7313,1.0305,1.0,4.0,0.0,4.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,1.0,0.0,3.0,1.0,1.0,0.0,1.0,0.0,1.0,11.0,3.0,0.0,1.0,4.0,2.0,3.0,0.0,97445,3239.1690,NaN,3966.9806,3262.1385,26443.0,98,3.2576,43,1.4294,31,243,8.0776,64861,45072,1498.2382,NaN,57758,0.131626,1.85,NaN,825.0,215,NaN,NaN,34.5706,15392.0,19165.0,318.0,14951.0,18911.0,312.0,441.0,254.0,6.0,0.0,0.0,1.0,1.0,0.0,0.0,24822.0,30988.0,541.0,23262.0,29909.0,516.0,1560.0,1079.0,25.0,1.0,2.0,1.0,1.0,0.0,1.0,35496.0,43331.0,696.0,33360.0,40399.0,669.0,2136.0,2932.0,27.0,5.0,14.0,4.0,4.0,7.0,5.0,47738.0,60226.0,874.0,43636.0,51932.0,808.0,4102.0,8294.0,66.0,13.0,34.0,8.0,8.0,18.0,13.0

In [49]:
df.shape

(120636, 165)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120636 entries, 0 to 120635
Columns: 165 entries, gameid to opp_deathsat25
dtypes: float64(122), int64(20), object(23)
memory usage: 151.9+ MB

In [51]:
df.describe()

,year,playoffs,game,patch,participantid,firstPick,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
count,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120504.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,110832.000000,110832.000000,110832.000000,110832.000000,112466.000000,100530.000000,92360.000000,92360.000000,120636.000000,120636.000000,20106.000000,20106.000000,20106.000000,18472.000000,18472.000000,18472.000000,18472.000000,18472.000000,18472.000000,18472.000000,18472.000000,1634.000000,18472.000000,18472.000000,18472.000000,20106.000000,20106.000000,20106.000000,20106.000000,18472.000000,112466.000000,112466.000000,18420.000000,18420.000000,20106.000000,20106.000000,20106.000000,18472.000000,18472.000000,18472.000000,18472.000000,112466.000000,112466.000000,120636.000000,120636.000000,100530.000000,120636.000000,110832.000000,110832.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,100530.000000,120636.000000,20106.000000,18472.000000,100530.00000,119002.000000,120636.000000,9804.000000,9804.000000,119002.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110832.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,110712.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000
mean,2025.024570,0.216055,1.830996,15.103810,29.583333,0.500000,1921.561027,0.500000,5.433519,5.446102,12.526924,16.300557,16.338307,0.625938,0.111213,0.017793,0.003302,0.287998,0.099990,0.141858,0.100000,0.514907,1.029815,0.499652,2.223068,2.223068,2.177945,2.177945,0.370940,0.366555,0.365526,0.367259,0.340894,0.366771,2.206854,0.046557,0.046557,0.498971,0.498956,0.498956,2.104596,2.104596,0.410838,0.181228,0.181228,0.485722,0.485722,0.500000,6.003034,6.003034,0.500000,0.500000,3.899199,3.899199,0.296605,0.296605,29702.566763,919.285062,0.200000,1278.369610,1190.514920,5426.984860,33.667562,1.042252,14.264482,0.437101,11.623545,82.363067,2.538899,19815.394857,12822.751534,400.386568,0.200000,18234.484350,0.000000,0.000000,207.95276,270.738013,67.909281,42.155753,4.846695,10.537264,5334.470027,6290.197290,109.790277,5334.470027,6290.197290,109.790277,0.000000,0.000000,0.000000,0.764508,1.174823,0.769200,0.764508,1.174823,0.769200,8325.908673,10025.317724,172.972986,8325.908673,10025.317724,172.972986,0.000000,0.000000,0.000000,1.486358,2.517432,1.492818,1.486358,2.517432,1.492818,11555.958252,14156.014633,231.573488,11555.958252,14156.014633,231.573488,0.000000,0.000000,0.000000,2.394844,4.602301,2.402648,2.394844,4.602301,2.402648,14695.877737,18290.032913,283.675738,14695.877737,18290.032913,283.675738,0.000000,0.000000,0.000000,3.433555,7.263683,3.442495,3.433555,7.263683,3.442495
std,0.154811,0.411554,0.982384,0.054828,57.650706,0.500002,327.906412,0.500002,6.488031,6.211593,14.660238,8.121588,8.121472,1.112498,0.367706,0.135501,0.057371,0.452832,0.299988,0.348906,0.300002,0.268917,0.297104,0.500012,1.363257,1.363257,1.319594,1.319594,0.659686,0.661765,0.655555,0.655991,0.656646,0.655975,1.302897,0.228920,0.228920,0.500012,0.500011,0.500011,1.736268,1.736268,0.491999,0.443472,0.443472,0.499810,0.499810,0.500012,3.630844,3.630844,0.500014,0.500014,2.538218,2.538218,0.646223,0.646223,30518.131041,900.109544,0.088240,1208.497517,1204.171618,6962.213605,36.680298,1.085562,15.158813,0.439735,12.681413,85.329098,2.501269,18592.195127,12331.336025,375.056798,0.061417,17120.377447,0.134171,2.137789,103.20685,271.947535,91.483895,65.075892,9.482728,9.851488,4808.881411,5696.401705,101.875838,4808.881411,5696.401705,101.875838,676.814581,560.118463,14.438268,1.255626,1.986121,1.221933,1.255626,1.986121,1.221933,7518.975301,9085.494365,160.558405,7518.975301,9085.494365,160.558405,1285.520059,1025.298349,21.397584,2.090256,3.535481,2.025775,2.090256,3.535481,2.025775,10461.350050,12833.065696,215.445465,10461.350050,12833.065696,215.445465,2091.218915,1800.190945,28.472184,3.119019,5.876514,3.012694,3.119019,5.876514,3.012694,13321.978526,16617.584346,264.332625,13321.978526,16617.584346,264.332625,2846.292261,3316.389635,34.947847,4.286042,8.859662,4.127327,4.286042,8.859662,4.127327
min,2025.000000,0.000000,1.000000,15.010000,1.000000,0.000000,1059.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.221100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,597.000000,25.049000,0.015857,4.405600,1.007000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3394.000000,201.000000,8.433600,0.008136,500.000000,-0.476673,-9.030000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1526.000000,0.000000,0.000000,1526.000000,0.000000,0.000000,-7330.000000,-5309.000000,-135.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2238.000000,0.000000,0.000000,2238.000000,0.000000,0.000000,-13867.000000,-9538.000000,-223.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2925.000000,80.000000,0.000000,2925.000000,80.000000,0.000000,-19248.000000,-14824.000000,-288.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4722.000000,3383.000000,6.000000,4722.000000,3383.000000,6.000000,-19544.000000,-26182.000000,-274.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2025.000000,0.000000,1.000000,15.070000,3.750000,0.000000,1696.000000,0.000000,1.000000,2.000000,4.000000,10.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.303900,0.817900,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,11389.000000,375.171350,0.131427,547.332000,390.520725,731.000000,10.000000,0.311975,5.000000,0.164200,3.000000,28.000000,0.909100,9907.000000,5926.000000,197.501325,0.168190,9150.000000,-0.101603,-1.520000,167.00000,34.000000,0.000000,0.000000,0.000000,6.096300,3077.000000,3318.000000,66.000000,3077.000000,3318.000000,66.000000,-301.000000,-304.000000,-7.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4735.000000,5527.000000,102.000000,4735.000000,5527.000000,102.000000,-540.000000,-505.000000,-11.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6512.000000,8007.000000,136.000000,6512.000000,8007.000000,136.000000,-849.000000,-805.000000,-14.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,8191.000000,10266.000000,165.000000,8191.000000,10266.000000,165.000000,-1172.000000,-1392.000000,-17.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000
50%,2025.000000,0.000000,2.000000,15.100000,6.500000,0.500000,1856.000000,0.500000,3.000000,4.000000,8.000000,16.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.488850,1.002400,0.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,7.000000,7.000000,0.500000,0.500000,3.000000,3.000000,0.000000,0.000000,18974.000000,607.157900,0.204518,771.866800,731.700200,2936.000000,14.000000,0.426000,9.000000,0.281400,7.000000,42.000000,1.280200,12600.000000,8447.000000,265.740800,0.210606,11558.000000,0.000000,0.000000,229.00000,234.000000,8.000000,2.000000,0.000000,7.915150,3376.000000,4118.000000,79.000000,3376.000000,4118.000000,79.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5272.000000,6629.000000,126.000000,5272.000000,6629.000000,126.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7368.000000,9380.000000,170.000000,7368.000000,9380.000000,170.000000,0.000000,0.000000,0.000000,1.000000,3.000000,2.000000,1.000000,3.000000,2.000000,9399.000000,12023.000000,208.000000,9399.000000,12023.000000,208.000000,0.000000,0.000000,0.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000
75%,2025.000000,0.000000,2.000000,15.150000,9.250000,1.000000,2103.000000,1.000000,7.000000,6.000000,14.000000,22.000000,22.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.694800,1.208100,1.000000,3.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,1.000000,3.000000,3.000000,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,9.000000,9.000000,1.000000,1.000000,5.000000,5.000000,0.000000,0.000000,30994.000000,925.524975,0.263843,1257.220575,1324.073450,6941.000000,53.000000,1.715400,16.000000,0.474200,15.000000,106.000000,3.395600,16203.000000,11534.000000,346.347825,0.243621,15010.000000,0.101603,1.520000,275.00000,303.000000,163.000000,113.000000,4.000000,9.408100,3778.000000,4900.000000,92.000000,3778.000000,4900.000000,92.000000,301.000000,304.000000,7.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,5996.000000,7729.000000,145.000000,5996.000000,7729.000000,145.000000,540.000000,505.000000,11.000000,2.000000,3.000000,2.000000,2.000000,3.000000,2.000000,8468.000000,10711.000000,196.000000,8468.000000,10711.000000,196.000000,849.000000,805.000000,14.000000,3.000000,5.000000,3.000000,3.000000,5.000000,3.000000,10924.000000,13821.250000,243.000000,10924.000000,13821.250000,243.000000,1172.000000,1392.000000,17.000000,4.000000,8.000000,4.000000,4.000000,8.000000,4.000000
max,2026.000000,1.000000,5.000000,15.240000,200.000000,1.000000,3621.000000,1.000000,48.000000,48.000000,128.000000,48.000000,48.000000,10.000000,4.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.102800,2.632100,1.000000,7.000000,7.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,3.000000,1.000000,1.000000,1.000000,6.000000,6.000000,1.000000,4.000000,4.000000,1.000000,1.000000,1.000000,15.000000,15.000000,1.000000,1.000000,15.000000,15.000000,10.000000,10.000000,315066.000000,5905.574500,0.605025,6901.387600,9420.020200,43467.000000,255.000000,4.960900,131.000000,2.913300,111.000000,611.000000,11.746400,116352.000000,78040.000000,1895.828100,0.412623,118860.000000,0.476673,9.030000,640.00000,1587.000000,431.000000,245.000000,73.000000,41.692800,22713.000000,21703.000000,411.000000,22713.000000,21703.000000,411.000000,7330.000000,5309.000000,135.000000,19.000000,35.000000,19.000000,19.000000,35.000000,19.000000,35963.000000,36444.000000,617.000000,35963.000000,36444.000000,617.000000,13867.000000,9538.000000,223.000000,27.000000,46.000000,27.000000,27.000000,46.000000,27.000000,49274.000000,53502.000000,850.000000,49274.000000,53502.000000,850.000000,19248.000000,14824.000000,288.000000,40.000000,78.000000,40.000000,40.000000,78.000000,40.000000,60330.000000,73801.000000,1066.000000,60330.000000,73801.000000,1066.000000,19544.000000,26182.000000,274.000000,42.000000,90.000000,42.000000,42.000000,90.000000,42.000000

In [52]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'url',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'playerid',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'dragons (type unknown)',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'atakhans',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [53]:
# All leagues on our dataframe
df['league'].unique()
# Vamos considerar as principais ligas no estudo, são elas: LTA S(antigo CBLOL), LTA N (antiga LCS), LCK, LPL, LEC
leagues = ['LTA S', 'LTA N', 'LCK', 'LPL', 'LEC']

In [58]:
new_df = df[df['league'].isin(leagues)].copy()
#new_df = new_df[new_df['year'] != 2026].copy()
new_df.head()

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
48,11715-11715_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=11715,LPL,2025,Split 1,0,2025-01-12 09:24:17,1,15.01,1,Blue,top,Breathe,oe:player:0d9b0a3b3a93a8f759c9d8ac8eef97c,Weibo Gaming,oe:team:606c6ac695907af3823ee6405c58ff1,1.0,K'Sante,Jayce,Poppy,Rumble,Rakan,Rell,NaN,NaN,NaN,NaN,NaN,2123,1,4,0,3,17,5,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.4805,0.6218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9830,277.8144,0.123949,747.1032,NaN,NaN,14,0.3957,3,0.0848,5,32,0.9044,14706,10099,285.4169,0.217523,12934,NaN,NaN,314.0,310.0,4,0.0,0.0,8.8742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,11715-11715_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=11715,LPL,2025,Split 1,0,2025-01-12 09:24:17,1,15.01,2,Blue,jng,Tian,oe:player:0da0eeb199e8fa3ab773cf84f9de9ab,Weibo Gaming,oe:team:606c6ac695907af3823ee6405c58ff1,1.0,Viego,Jayce,Poppy,Rumble,Rakan,Rell,NaN,NaN,NaN,NaN,NaN,2123,1,4,0,5,17,5,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.4805,0.6218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10013,282.9863,0.126255,1207.4611,NaN,NaN,13,0.3674,14,0.3957,12,55,1.5544,14586,9979,282.0254,0.214939,13193,NaN,NaN,273.0,35.0,238,0.0,0.0,7.7155,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,11715-11715_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=11715,LPL,2025,Split 1,0,2025-01-12 09:24:17,1,15.01,3,Blue,mid,Xiaohu,oe:player:beea9fe15bff6a7ab0b3913d3d5fde6,Weibo Gaming,oe:team:606c6ac695907af3823ee6405c58ff1,1.0,Aurora,Jayce,Poppy,Rumble,Rakan,Rell,NaN,NaN,NaN,NaN,NaN,2123,1,5,1,8,17,5,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.4805,0.6218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37571,1061.8276,0.473724,477.0890,NaN,NaN,11,0.3109,11,0.3109,7,43,1.2153,15720,11113,314.0744,0.239363,14249,NaN,NaN,286.0,282.0,4,0.0,0.0,8.0829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,11715-11715_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=11715,LPL,2025,Split 1,0,2025-01-12 09:24:17,1,15.01,4,Blue,bot,Light,oe:player:3c4d21c7addb20fea3fec30418ac3d3,Weibo Gaming,oe:team:606c6ac695907af3823ee6405c58ff1,1.0,Ashe,Jayce,Poppy,Rumble,Rakan,Rell,NaN,NaN,NaN,NaN,NaN,2123,1,3,2,6,17,5,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.4805,0.6218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15603,440.9703,0.196738,432.1526,NaN,NaN,9,0.2544,17,0.4805,3,57,1.6109,14688,10081,284.9081,0.217136,13169,NaN,NaN,305.0,284.0,21,0.0,0.0,8.6199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,11715-11715_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=11715,LPL,2025,Split 1,0,2025-01-12 09:24:17,1,15.01,5,Blue,sup,Hang,oe:player:ab2455e33b8ddb6a9d2d41107a2ed4f,Weibo Gaming,oe:team:606c6ac695907af3823ee6405c58ff1,1.0,Braum,Jayce,Poppy,Rumble,Rakan,Rell,NaN,NaN,NaN,NaN,NaN,2123,1,1,2,11,17,5,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.4805,0.6218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6292,177.8238,0.079335,507.6401,NaN,NaN,67,1.8935,20,0.5652,19,144,4.0697,9762,5155,145.6901,0.111039,8620,NaN,NaN,38.0,38.0,0,0.0,0.0,1.0740,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
new_df.tail()

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
116143,LOLTMNT03_306785,complete,NaN,LTA N,2026,NaN,0,2025-10-12 22:55:28,4,15.19,8,Red,mid,Insanity,oe:player:ef97df9d746d0e65ed18786ab30031c,Luminosity Gaming,oe:team:f59945d4b3a3148637047638acb88b7,0.0,Kog'Maw,Orianna,Viktor,Sion,Blitzcrank,Ashe,NaN,NaN,NaN,NaN,NaN,2469,0,9,3,4,14,15,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3402,0.7047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,37273,905.7837,0.345293,395.3584,289.8663,4299.0,23,0.5589,7,0.1701,8,51,1.2394,16306,10994,267.1689,0.235102,15650,NaN,NaN,280.0,276.0,4,NaN,NaN,6.8044,3475.0,5009.0,97.0,3662.0,4957.0,94.0,-187.0,52.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,5348.0,7707.0,154.0,5786.0,7131.0,138.0,-438.0,576.0,16.0,0.0,0.0,0.0,1.0,0.0,0.0,7177.0,9426.0,175.0,7563.0,9576.0,187.0,-386.0,-150.0,-12.0,1.0,0.0,0.0,1.0,1.0,1.0,9099.0,11963.0,196.0,9476.0,11545.0,220.0,-377.0,418.0,-24.0,2.0,4.0,0.0,2.0,3.0,1.0
116144,LOLTMNT03_306785,complete,NaN,LTA N,2026,NaN,0,2025-10-12 22:55:28,4,15.19,9,Red,bot,Tactical,oe:player:4e0619e57cb50c4ab1230c2dd72df1b,Luminosity Gaming,oe:team:f59945d4b3a3148637047638acb88b7,0.0,Ezreal,Orianna,Viktor,Sion,Blitzcrank,Ashe,NaN,NaN,NaN,NaN,NaN,2469,0,3,3,4,14,15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3402,0.7047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,23703,576.0146,0.219582,565.9538,334.7752,4238.0,18,0.4374,15,0.3645,6,48,1.1665,16138,10826,263.0863,0.231509,15383,NaN,NaN,358.0,350.0,8,NaN,NaN,8.6999,3430.0,3767.0,95.0,3604.0,3668.0,96.0,-174.0,99.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,5289.0,6437.0,155.0,5280.0,5485.0,145.0,9.0,952.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,7420.0,9000.0,214.0,7899.0,7588.0,205.0,-479.0,1412.0,9.0,0.0,0.0,0.0,0.0,1.0,0.0,10783.0,12481.0,263.0,9971.0,9377.0,245.0,812.0,3104.0,18.0,3.0,2.0,0.0,2.0,2.0,1.0
116145,LOLTMNT03_306785,complete,NaN,LTA N,2026,NaN,0,2025-10-12 22:55:28,4,15.19,10,Red,sup,Zeyzal,oe:player:6841f2d68619d53bdd1cdbf30b5be2c,Luminosity Gaming,oe:team:f59945d4b3a3148637047638acb88b7,0.0,Pantheon,Orianna,Viktor,Sion,Blitzcrank,Ashe,NaN,NaN,NaN,NaN,NaN,2469,0,1,6,6,14,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3402,0.7047,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7834,190.3767,0.072573,800.3402,546.0753,0.0,69,1.6768,20,0.4860,22,137,3.3293,9388,4076,99.0522,0.087159,9050,NaN,NaN,44.0,44.0,0,NaN,NaN,1.0693,2078.0,2440.0,15.0,2378.0,2487.0,16.0,-300.0,-47.0,-1.0,0.0,0.0,1.0,0.0,1.0,0.0,3125.0,3031.0,26.0,3504.0,3474.0,26.0,-379.0,-443.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,4328.0,4268.0,33.0,4880.0,5064.0,28.0,-552.0,-796.0,5.0,0.0,1.0,2.0,1.0,1.0,0.0,5795.0,6611.0,34.0,5930.0,6858.0,30.0,-135.0,-247.0,4.0,1.0,2.0,4.0,1.0,4.0,1.0
116146,LOLTMNT03_306785,complete,NaN,LTA N,2026,NaN,0,2025-10-12 22:55:28,4,15.19,100,Blue,team,NaN,NaN,Disguised,oe:team:289284911fb6f41c0ccaecc3a0c2891,1.0,NaN,Neeko,LeBlanc,Trundle,Bard,Karma,Ziggs,Skarner,Jax,Jinx,Lulu,2469,1,15,14,44,15,14,2.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,0.3645,0.7047,0.0,4.0,3.0,4.0,3.0,0.0,1.0,0.0,0.0,3.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0,0.0,1.0,1.0,9.0,5.0,1.0,1.0,5.0,2.0,2.0,0.0,105052,2552.9040,NaN,3392.5152,3873.0498,25291.0,165,4.0097,71,1.7254,61,373,9.0644,76802,50240,1220.8991,NaN,68258,-0.035091,-0.13,NaN,1112.0,266,NaN,NaN,33.4872,15966.0,19224.0,354.0,15557.0,19958.0,369.0,409.0,-734.0,-15.0,1.0,2.0,0.0,0.0,0.0,1.0,24718.0,30042.0,567.0,23393.0,30427.0,578.0,1325.0,-385.0,-11.0,1.0,2.0,0.0,0.0,0.0,1.0,34231.0,41333.0,762.0,33235.0,42811.0,768.0,996.0,-1478.0,-6.0,2.0,5.0,1.0,1.0,3.0,2.0,41819.0,49891.0,886.0,44530.0,57587.0,921.0,-2711.0,-7696.0,-35.0,5.0,14.0,7.0,7.0,15.0,5.0
116147,LOLTMNT03_306785,complete,NaN,LTA N,2026,NaN,0,2025-10-12 22:55:28,4,15.19,200,Red,team,NaN,NaN,Luminosity Gaming,oe:team:f59945d4b3a3148637047638acb88b7,0.0,NaN,Orianna,Viktor,Sion,Blitzcrank,Ashe,Ezreal,Pantheon,Gnar,Nidalee,Kog'Maw,2469,0,14,15,33,14,15,2.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3402,0.7047,1.0,3.0,4.0,3.0,4.0,0.0,0.0,0.0,1.0,2.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,5.0,9.0,0.0,0.0,2.0,5.0,0.0,2.0,107946,2623.2321,NaN,3672.9040,3065.3706,19370.0,128,3.1106,91,2.2114,46,393,9.5504,73323,46761,1136.3548,NaN,70696,0.035091,0.13,NaN,1048.0,307,NaN,NaN,32.9283,15557.0,19958.0,369.0,15966.0,19224.0,354.0,-409.0,734.0,15.0,0.0,0.0,1.0,1.0,2.0,0.0,23393.0,30427.0,578.0,24718.0,30042.0,567.0,-1325.0,385.0,11.0,0.0,0.0,1.0,1.0,2.0,0.0,33235.0,42811.0,768.0,34231.0,41333.0,762.0,-996.0,1478.0,6.0,1.0,3.0,2.0,2.0,5.0,1.0,44530.0,57587.0,921.0,41819.0,49891.0,886.0,2711.0,7696.0,35.0,7.0,15.0,5.0,5.0,14.0,7.0