# Análise de Dados e Boas Práticas
## Análise do cenário competitivo de League of Legends
Hugo Leandro Antunes

## 1. Definição do Problema
O dataset utilizado contém informações de partidas profissionas do jogo eletrônico League of Legends, além de ser de domínio público, e pode ser encontrado em https://oracleselixir.com/, onde é disponibilizado em um Google Drive (https://drive.google.com/drive/u/1/folders/1gLSw0RLjBbtaNy0dgnGQDAZOHIgCe-HH).

O dataset contém informações muito valiosas para análise de jogadores, escolha de campeões, de objetivos, escolha de lado e análises pós partidas. Essas informações são pouquíssimas exploradas pela comunidade de League of Legends brasileira, sendo uma área muito explorável para disseminação de informações e maior compreendimento do cenário competitivo. Para detalhes mais aprofundados sobre o que cada dado significa, explicações gerais do jogo, rotas, campeões, funções e regiões; poderá ser encontrado na documentação ./docs/.

A análise que será explorada aqui tem como objetivo explorar as seguintes questões do cenário competitivo de League of Legends:
- Como as 5 principais ligas se diferenciam entre si em relação a estilo de jogo e prioridade no jogo;
- Quais foram as principais mudanças competitivas no jogo ao decorrer de 10 anos. Temos dados desde 2015, sendo possível fazer uma análise histórica robusta;
- Análise de campeões: como os campeões tem prioridade e como desempenham durante as partidas em determinado ano
Entendo que há uma carência muito grande sobre análises robustas desses dados, diferente do que acontece nos outros esportes, onde há muita falta de dados, jogos eletrônicos tem uma abundância dessas informações, o que é geralmente muito pouco explorada.

In [2]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

In [8]:
url = 'https://raw.githubusercontent.com/hugo-antunes19/analise-dados-puc-hugo-antunes/refs/heads/main/data/2025_LoL_esports_match_data_from_OraclesElixir.csv'
df = pd.read_csv(url, delimiter=',')

/tmp/ipykernel_953/2740451776.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url, delimiter=',')

In [10]:
df.head(10)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,200.0,224.0,-1.0,17.0,1.0,1.0,2.0,2.0,4.0,2.0
1,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,157.0,-2363.0,-1444.0,-18.0,0.0,1.0,2.0,1.0,7.0,0.0
2,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,241.0,-1552.0,-2465.0,-41.0,1.0,0.0,2.0,1.0,5.0,1.0
3,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,257.0,-2613.0,-1156.0,-6.0,1.0,1.0,2.0,6.0,2.0,0.0
4,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,20.0,-662.0,-734.0,18.0,0.0,2.0,2.0,0.0,8.0,0.0
5,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,217.0,-224.0,1.0,-17.0,2.0,4.0,2.0,1.0,1.0,2.0
6,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,139.0,2363.0,1444.0,18.0,1.0,7.0,0.0,0.0,1.0,2.0
7,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,200.0,1552.0,2465.0,41.0,1.0,5.0,1.0,1.0,0.0,2.0
8,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,251.0,2613.0,1156.0,6.0,6.0,2.0,0.0,1.0,1.0,2.0
9,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,38.0,662.0,734.0,-18.0,0.0,8.0,0.0,0.0,2.0,2.0

In [11]:
df.tail(10)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
120626,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,192.0,125.0,500.0,32.0,4.0,4.0,1.0,8.0,5.0,2.0
120627,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,226.0,541.0,-513.0,-5.0,2.0,4.0,2.0,0.0,7.0,2.0
120628,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,48.0,-1255.0,-2399.0,-17.0,1.0,1.0,4.0,1.0,9.0,1.0
120629,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,188.0,1763.0,3518.0,31.0,2.0,5.0,2.0,0.0,5.0,3.0
120630,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,144.0,1750.0,2364.0,45.0,2.0,8.0,1.0,1.0,4.0,3.0
120631,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,224.0,-125.0,-500.0,-32.0,8.0,5.0,2.0,4.0,4.0,1.0
120632,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,221.0,-541.0,513.0,5.0,0.0,7.0,2.0,2.0,4.0,2.0
120633,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,31.0,1255.0,2399.0,17.0,1.0,9.0,1.0,1.0,1.0,4.0
120634,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,874.0,-4102.0,-8294.0,-66.0,8.0,18.0,13.0,13.0,34.0,8.0
120635,LOLTMNT03_332179,complete,NaN,DCup,2025,NaN,0,2025-12-29 10:52:27,3,15.24,...,808.0,4102.0,8294.0,66.0,13.0,34.0,8.0,8.0,18.0,13.0

In [12]:
df.shape

(120636, 165)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120636 entries, 0 to 120635
Columns: 165 entries, gameid to opp_deathsat25
dtypes: float64(122), int64(20), object(23)
memory usage: 151.9+ MB

In [15]:
df.describe()

,year,playoffs,game,patch,participantid,firstPick,gamelength,result,kills,deaths,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
count,120636.000000,120636.000000,120636.000000,120636.000000,120636.000000,120504.000000,120636.000000,120636.000000,120636.000000,120636.000000,...,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000,106704.000000
mean,2025.024570,0.216055,1.830996,15.103810,29.583333,0.500000,1921.561027,0.500000,5.433519,5.446102,...,283.675738,0.000000,0.000000,0.000000,3.433555,7.263683,3.442495,3.433555,7.263683,3.442495
std,0.154811,0.411554,0.982384,0.054828,57.650706,0.500002,327.906412,0.500002,6.488031,6.211593,...,264.332625,2846.292261,3316.389635,34.947847,4.286042,8.859662,4.127327,4.286042,8.859662,4.127327
min,2025.000000,0.000000,1.000000,15.010000,1.000000,0.000000,1059.000000,0.000000,0.000000,0.000000,...,6.000000,-19544.000000,-26182.000000,-274.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2025.000000,0.000000,1.000000,15.070000,3.750000,0.000000,1696.000000,0.000000,1.000000,2.000000,...,165.000000,-1172.000000,-1392.000000,-17.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000
50%,2025.000000,0.000000,2.000000,15.100000,6.500000,0.500000,1856.000000,0.500000,3.000000,4.000000,...,208.000000,0.000000,0.000000,0.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000
75%,2025.000000,0.000000,2.000000,15.150000,9.250000,1.000000,2103.000000,1.000000,7.000000,6.000000,...,243.000000,1172.000000,1392.000000,17.000000,4.000000,8.000000,4.000000,4.000000,8.000000,4.000000
max,2026.000000,1.000000,5.000000,15.240000,200.000000,1.000000,3621.000000,1.000000,48.000000,48.000000,...,1066.000000,19544.000000,26182.000000,274.000000,42.000000,90.000000,42.000000,42.000000,90.000000,42.000000